//! portcourt doc-generation + staleness gate.
//!
//! The authoritative CLI reference (`docs/CLI.md`) is **generated** from the command model below, never
//! hand-edited. `xtask docs generate` writes it; `xtask docs check` regenerates it in memory and fails
//! (nonzero exit) if the committed file has drifted — the same anti-staleness discipline portcourt itself
//! enforces on a port's claims. `xtask gate` runs the doc check plus `cargo test` plus a portcourt
//! self-check, the one command CI runs.

use std::path::Path;
use std::process::{Command, ExitCode};

/// One portcourt subcommand, the single source of truth for its documentation.
struct Cmd {
    name: &'static str,
    args: &'static str,
    summary: &'static str,
    detail: &'static str,
}

const COMMANDS: &[Cmd] = &[
    Cmd {
        name: "check",
        args: "[config.toml]",
        summary: "the gate — verify every module's claim against the evidence",
        detail: "Closure math: for each `[module]` in the config, a `claim = \"complete\"` module must have \
                 zero missing functions and zero doc-only false hits on compiled functions; a `min_parity` \
                 sets a floor on active parity; and every court in `requires` must be sealed in the claim \
                 ladder. Any over-claim prints `✗ …` and the process exits non-zero, so `check` is a build \
                 gate. Modules present in the parity view but undeclared in the config are surfaced as a \
                 note, never silently ignored.",
    },
    Cmd {
        name: "explain",
        args: "<fn> [config.toml]",
        summary: "the port status of one function",
        detail: "Locates `<fn>` across every module in the parity view and reports whether it is PORTED, \
                 MISSING (no Rust `fn`), DOC-ONLY (a name that appears only in a comment — a false hit, not \
                 a port), or DISABLED (`#if 0` in the C, not a port target), along with the Rust module that \
                 ports it and any court whose `proven` prose names it.",
    },
    Cmd {
        name: "next",
        args: "[file] [config.toml]",
        summary: "the porting driver — which functions are still missing",
        detail: "Lists, per module (or for one `file`), the functions whose status is `missing` (no port \
                 yet) and `doc_only` (a comment to reword). This is the worklist a port drives off of.",
    },
    Cmd {
        name: "report",
        args: "[config.toml]",
        summary: "the parity table across all modules",
        detail: "Prints active parity %, ported / missing / doc-only / disabled counts per module and a \
                 grand total — the whole port at a glance.",
    },
];

/// Render the generated CLI reference from the command model.
fn render_cli() -> String {
    let mut s = String::new();
    s.push_str("<!-- GENERATED by `cargo run -p xtask -- docs generate`. DO NOT EDIT BY HAND. -->\n");
    s.push_str("<!-- Source of truth: xtask/src/main.rs `COMMANDS`. Staleness-gated by `xtask docs check`. -->\n\n");
    s.push_str("# portcourt — CLI reference\n\n");
    s.push_str("A general C→Rust port evidence court. All paths in the config resolve relative to the \
                config file; the config defaults to `./portcourt.toml`.\n\n");
    s.push_str("| command | summary |\n|---|---|\n");
    for c in COMMANDS {
        s.push_str(&format!("| `portcourt {} {}` | {} |\n", c.name, c.args, c.summary));
    }
    s.push('\n');
    for c in COMMANDS {
        s.push_str(&format!("## `portcourt {} {}`\n\n{}\n\n{}\n\n", c.name, c.args, c.summary, c.detail));
    }
    s.push_str("---\n\n_Generated document. Edit `xtask/src/main.rs` and run `cargo run -p xtask -- docs generate`._\n");
    s
}

fn repo_root() -> std::path::PathBuf {
    // xtask runs from the workspace; the manifest dir is <root>/xtask.
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

fn cli_path() -> std::path::PathBuf {
    repo_root().join("docs/CLI.md")
}

fn docs_generate() -> ExitCode {
    let root = repo_root();
    let _ = std::fs::create_dir_all(root.join("docs"));
    let out = render_cli();
    match std::fs::write(cli_path(), &out) {
        Ok(()) => {
            println!("portcourt-docs: generated docs/CLI.md ({} commands)", COMMANDS.len());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("portcourt-docs: write failed: {e}");
            ExitCode::FAILURE
        }
    }
}

fn docs_check() -> ExitCode {
    let want = render_cli();
    let have = std::fs::read_to_string(cli_path()).unwrap_or_default();
    if have == want {
        println!("portcourt-docs: docs/CLI.md is fresh");
        ExitCode::SUCCESS
    } else {
        eprintln!("portcourt-docs: STALE — docs/CLI.md != regenerate(model). Run `cargo run -p xtask -- docs generate`.");
        ExitCode::FAILURE
    }
}

fn run(cmd: &mut Command) -> bool {
    cmd.status().map(|s| s.success()).unwrap_or(false)
}

fn gate() -> ExitCode {
    let root = repo_root();
    let mut ok = true;
    print!("portcourt-gate: docs fresh ... ");
    if docs_check() == ExitCode::SUCCESS {
        println!("ok");
    } else {
        ok = false;
    }
    print!("portcourt-gate: cargo test ... ");
    if run(Command::new("cargo").arg("test").arg("--quiet").current_dir(&root)) {
        println!("ok");
    } else {
        println!("FAIL");
        ok = false;
    }
    print!("portcourt-gate: self-check against own config ... ");
    let built = run(Command::new("cargo").args(["build", "--quiet"]).current_dir(&root));
    let selfcheck = built
        && Command::new(root.join("target/debug/portcourt"))
            .args(["check", "portcourt.selftest.toml"])
            .current_dir(&root)
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
    if selfcheck {
        println!("ok");
    } else {
        println!("FAIL");
        ok = false;
    }
    if ok {
        println!("\nPORTCOURT-GATE: PASS");
        ExitCode::SUCCESS
    } else {
        println!("\nPORTCOURT-GATE: FAIL");
        ExitCode::FAILURE
    }
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match (args.first().map(String::as_str), args.get(1).map(String::as_str)) {
        (Some("docs"), Some("generate")) => docs_generate(),
        (Some("docs"), Some("check")) => docs_check(),
        (Some("gate"), _) => gate(),
        _ => {
            eprintln!("usage: xtask <docs generate|docs check|gate>");
            ExitCode::FAILURE
        }
    }
}
