//! portcourt doc-generation + staleness gate.
//!
//! The authoritative CLI reference (`docs/CLI.md`) is **generated** from the command model below, never
//! hand-edited. `xtask docs generate` writes it; `xtask docs check` regenerates it in memory and fails
//! (nonzero exit) if the committed file has drifted — the same anti-staleness discipline portcourt itself
//! enforces on a port's claims. `xtask gate` runs the doc check plus `cargo test` plus a portcourt
//! self-check, the one command CI runs.

use std::path::Path;
use std::process::{Command, ExitCode};

/// One portcourt subcommand, the single source of truth for its documentation.
struct Cmd {
    name: &'static str,
    args: &'static str,
    summary: &'static str,
    detail: &'static str,
}

const COMMANDS: &[Cmd] = &[
    Cmd {
        name: "check",
        args: "[config.toml]",
        summary: "the gate — verify every module's claim against the evidence",
        detail: "Closure math: for each `[module]` in the config, a `claim = \"complete\"` module must have \
                 zero missing functions and zero doc-only false hits on compiled functions; a `min_parity` \
                 sets a floor on active parity; and every court in `requires` must be sealed in the claim \
                 ladder. Any over-claim prints `✗ …` and the process exits non-zero, so `check` is a build \
                 gate. Modules present in the parity view but undeclared in the config are surfaced as a \
                 note, never silently ignored.",
    },
    Cmd {
        name: "explain",
        args: "<fn> [config.toml]",
        summary: "the port status of one function",
        detail: "Locates `<fn>` across every module in the parity view and reports whether it is PORTED, \
                 MISSING (no Rust `fn`), DOC-ONLY (a name that appears only in a comment — a false hit, not \
                 a port), or DISABLED (`#if 0` in the C, not a port target), along with the Rust module that \
                 ports it and any court whose `proven` prose names it.",
    },
    Cmd {
        name: "next",
        args: "[file] [config.toml]",
        summary: "the porting driver — which functions are still missing",
        detail: "Lists, per module (or for one `file`), the functions whose status is `missing` (no port \
                 yet) and `doc_only` (a comment to reword). This is the worklist a port drives off of.",
    },
    Cmd {
        name: "report",
        args: "[config.toml]",
        summary: "the parity table across all modules",
        detail: "Prints active parity %, ported / missing / doc-only / disabled counts per module and a \
                 grand total — the whole port at a glance.",
    },
];

/// Render the crate README from the command model. The command table is derived from `COMMANDS` so it can
/// never drift from the actual CLI — the same single source of truth that drives `docs/CLI.md`.
fn render_readme() -> String {
    let mut s = String::new();
    s.push_str("<!-- GENERATED by `cargo run -p xtask -- docs generate`. DO NOT EDIT BY HAND. -->\n");
    s.push_str("<!-- Source of truth: xtask/src/main.rs (`COMMANDS` + `render_readme`). Gated by `xtask docs check`. -->\n\n");
    s.push_str("# portcourt\n\n");
    s.push_str(
        "A general **C→Rust port evidence court**. A faithful port lives or dies by one question: *is the \
         claim backed by the evidence?* portcourt makes that mechanical.\n\n",
    );
    s.push_str(
        "It consumes the parity view a port already produces — the typed join of every C source symbol \
         against the real Rust `fn` that ports it (`active` / `missing` / `doc_only` / `disabled`) — plus a \
         small declaration of what each module *claims*, and enforces **closure math**:\n\n",
    );
    s.push_str(
        "> A module that claims to be `complete` must have **zero missing functions** and **zero doc-only \
         false hits on compiled functions**, and every court it `requires` must actually be **sealed** — \
         otherwise the build fails. You cannot claim more than the evidence proves.\n\n",
    );
    s.push_str("## Commands\n\n| command | summary |\n|---|---|\n");
    for c in COMMANDS {
        s.push_str(&format!("| `portcourt {} {}` | {} |\n", c.name, c.args, c.summary));
    }
    s.push_str("\nThe full per-command reference is generated into [`docs/CLI.md`](docs/CLI.md).\n\n");
    s.push_str("## 60-second demo\n\n");
    s.push_str(
        "The [`examples/`](examples/) directory has a tiny self-contained port — a parity view \
         ([`parity.min.json`](examples/parity.min.json)), a claim ladder \
         ([`claim-ladder.min.json`](examples/claim-ladder.min.json)), an honest claim set \
         ([`honest.toml`](examples/honest.toml)), and an over-claim set \
         ([`overclaim.toml`](examples/overclaim.toml)). The money shot:\n\n",
    );
    s.push_str("```text\n");
    s.push_str("$ portcourt check examples/overclaim.toml\n");
    s.push_str("  [FAIL] alpha.c        100.0%  ported   2  missing   0  doc-only  1  (1 required court(s))\n");
    s.push_str("         - requires court `COURT.BETA.OPEN` which is not sealed\n");
    s.push_str("  [FAIL] beta.c          33.3%  ported   1  missing   1  doc-only  1  (0 required court(s))\n");
    s.push_str("         - claims `complete` but has 1 missing + 1 doc-only on compiled functions (over-claim)\n");
    s.push_str("\nPORTCOURT: FAIL — 2 over-claim(s):\n");
    s.push_str("```\n\n");
    s.push_str(
        "The full, live-captured transcript (report / next / explain / check on both honest and over-claim \
         configs) is generated into [`examples/TRANSCRIPT.md`](examples/TRANSCRIPT.md) — it is the tool's \
         real output, staleness-gated so it cannot lie.\n\n",
    );
    s.push_str("## Config (`portcourt.toml`)\n\n");
    s.push_str("```toml\n");
    s.push_str("parity = \"reports/port-index/parity-detailed.json\"   # the C↔Rust symbol join (per file, per fn)\n");
    s.push_str("courts = \"reports/claim-ladder.json\"                  # optional: the sealed courts, for `requires`\n\n");
    s.push_str("[module.\"fileio.c\"]\n");
    s.push_str("claim = \"complete\"                                    # complete | partial\n");
    s.push_str("requires = [\"GNURUST.FILEIO.INDEXED.1\", \"...\"]        # courts that must be sealed for this claim\n\n");
    s.push_str("[module.\"common.c\"]\n");
    s.push_str("claim = \"partial\"\n");
    s.push_str("min_parity = 0.0                                      # optional floor on active parity %\n");
    s.push_str("```\n\n");
    s.push_str(
        "The parity JSON is any array of \
         `{ \"file\": \"...\", \"fns\": [{ \"function\", \"rust_status\", \"preprocessor_status\" }] }`. \
         portcourt is deliberately port-agnostic: point it at your parity view and claim ladder and it \
         works.\n\n",
    );
    s.push_str("## Why \"closure math\"\n\n");
    s.push_str(
        "The name is the discipline: a claim is a *closure* over its evidence. `check` computes whether the \
         closure holds — every required court sealed, every compiled function ported, no doc-only inflation \
         — and refuses to let a port assert completeness it hasn't earned. It is the same anti-over-claim \
         rule a careful port already applies by hand, made into a gate.\n\n",
    );
    s.push_str("## Generated docs + staleness gate\n\n");
    s.push_str(
        "This README and `docs/CLI.md` are generated by `cargo run -p xtask -- docs generate` from the \
         command model in `xtask/src/main.rs`. `cargo run -p xtask -- docs check` fails if either file has \
         drifted, and `cargo run -p xtask -- gate` runs that check plus `cargo test` plus a self-check — \
         the same anti-staleness discipline portcourt enforces on a port's claims.\n\n",
    );
    s.push_str("## License\n\n");
    s.push_str(
        "Apache-2.0. No dependency on, or derivation from, any ported source — portcourt only reads \
         evidence.\n",
    );
    s
}

/// Render the generated CLI reference from the command model.
fn render_cli() -> String {
    let mut s = String::new();
    s.push_str("<!-- GENERATED by `cargo run -p xtask -- docs generate`. DO NOT EDIT BY HAND. -->\n");
    s.push_str("<!-- Source of truth: xtask/src/main.rs `COMMANDS`. Staleness-gated by `xtask docs check`. -->\n\n");
    s.push_str("# portcourt — CLI reference\n\n");
    s.push_str("A general C→Rust port evidence court. All paths in the config resolve relative to the \
                config file; the config defaults to `./portcourt.toml`.\n\n");
    s.push_str("| command | summary |\n|---|---|\n");
    for c in COMMANDS {
        s.push_str(&format!("| `portcourt {} {}` | {} |\n", c.name, c.args, c.summary));
    }
    s.push('\n');
    for c in COMMANDS {
        s.push_str(&format!("## `portcourt {} {}`\n\n{}\n\n{}\n\n", c.name, c.args, c.summary, c.detail));
    }
    s.push_str("---\n\n_Generated document. Edit `xtask/src/main.rs` and run `cargo run -p xtask -- docs generate`._\n");
    s
}

fn repo_root() -> std::path::PathBuf {
    // xtask runs from the workspace; the manifest dir is <root>/xtask.
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

/// Every PURE generated document: the path (relative to the repo root) and its renderer. Adding a generated
/// doc is a one-line entry here — both `docs generate` and `docs check` iterate this table, so they can
/// never disagree about what is generated. (The demo transcript is generated by EXECUTION, not pure
/// rendering, so it is handled separately by [`render_transcript`].)
fn generated_docs() -> Vec<(&'static str, fn() -> String)> {
    vec![("docs/CLI.md", render_cli as fn() -> String), ("README.md", render_readme as fn() -> String)]
}

/// The demo commands run against `examples/` to produce the transcript. The last one is an over-claim that
/// is EXPECTED to exit non-zero — the transcript captures its output regardless, because the failing case
/// is the whole point of the demo.
const DEMO: &[&[&str]] = &[
    &["report", "examples/honest.toml"],
    &["next", "beta.c", "examples/honest.toml"],
    &["explain", "b_write", "examples/honest.toml"],
    &["check", "examples/honest.toml"],
    &["check", "examples/overclaim.toml"],
];

/// Run the portcourt binary against the example fixtures and assemble a transcript. Because it is the tool's
/// REAL output — captured live, then gated like any other generated doc — the demo can never drift from
/// what portcourt actually prints. If the output format ever changes, `docs check` fails until the
/// transcript is regenerated.
fn render_transcript() -> String {
    let root = repo_root();
    // Build the binary once so each demo command runs the current code (not a stale target/).
    let _ = Command::new("cargo").args(["build", "--quiet", "-p", "portcourt"]).current_dir(&root).status();
    let bin = root.join("target/debug/portcourt");

    let mut s = String::new();
    s.push_str("<!-- GENERATED by `cargo run -p xtask -- docs generate` (runs portcourt against examples/). DO NOT EDIT BY HAND. -->\n\n");
    s.push_str("# portcourt — demo transcript\n\n");
    s.push_str(
        "Every block below is the **real, captured output** of running portcourt against the fixtures in \
         [`examples/`](.). It is regenerated by running the tool and is staleness-gated, so it cannot lie \
         about what portcourt prints.\n\n",
    );
    for cmd in DEMO {
        let out = Command::new(&bin).args(*cmd).current_dir(&root).output();
        let (stdout, code) = match out {
            Ok(o) => (String::from_utf8_lossy(&o.stdout).into_owned(), o.status.code().unwrap_or(-1)),
            Err(e) => (format!("<could not run portcourt: {e}>\n"), -1),
        };
        s.push_str(&format!("### `$ portcourt {}`\n\n", cmd.join(" ")));
        s.push_str("```text\n");
        s.push_str(stdout.trim_end_matches('\n'));
        s.push('\n');
        s.push_str("```\n");
        s.push_str(&format!("_exit code: {code}_\n\n"));
    }
    s.push_str("---\n\n_Generated by `cargo run -p xtask -- docs generate`; gated by `docs check`._\n");
    s
}

fn transcript_path() -> std::path::PathBuf {
    repo_root().join("examples/TRANSCRIPT.md")
}

fn docs_generate() -> ExitCode {
    let root = repo_root();
    let _ = std::fs::create_dir_all(root.join("docs"));
    for (rel, render) in generated_docs() {
        let path = root.join(rel);
        if let Err(e) = std::fs::write(&path, render()) {
            eprintln!("portcourt-docs: write {rel} failed: {e}");
            return ExitCode::FAILURE;
        }
        println!("portcourt-docs: generated {rel}");
    }
    if let Err(e) = std::fs::write(transcript_path(), render_transcript()) {
        eprintln!("portcourt-docs: write examples/TRANSCRIPT.md failed: {e}");
        return ExitCode::FAILURE;
    }
    println!("portcourt-docs: generated examples/TRANSCRIPT.md");
    ExitCode::SUCCESS
}

fn docs_check() -> ExitCode {
    let root = repo_root();
    // Collect ALL stale documents before reporting, so one run names every drifted file rather than the
    // first — the same "report everything at once" stance portcourt's own `check` takes.
    let mut stale: Vec<String> = Vec::new();
    for (rel, render) in generated_docs() {
        let have = std::fs::read_to_string(root.join(rel)).unwrap_or_default();
        if have != render() {
            stale.push(rel.to_string());
        }
    }
    if std::fs::read_to_string(transcript_path()).unwrap_or_default() != render_transcript() {
        stale.push("examples/TRANSCRIPT.md".to_string());
    }
    if stale.is_empty() {
        println!("portcourt-docs: all generated docs are fresh ({} pure + transcript)", generated_docs().len());
        ExitCode::SUCCESS
    } else {
        eprintln!(
            "portcourt-docs: STALE — {} != regenerate(model). Run `cargo run -p xtask -- docs generate`.",
            stale.join(", ")
        );
        ExitCode::FAILURE
    }
}

fn run(cmd: &mut Command) -> bool {
    cmd.status().map(|s| s.success()).unwrap_or(false)
}

fn gate() -> ExitCode {
    let root = repo_root();
    let mut ok = true;
    print!("portcourt-gate: docs fresh ... ");
    if docs_check() == ExitCode::SUCCESS {
        println!("ok");
    } else {
        ok = false;
    }
    print!("portcourt-gate: cargo test ... ");
    if run(Command::new("cargo").arg("test").arg("--quiet").current_dir(&root)) {
        println!("ok");
    } else {
        println!("FAIL");
        ok = false;
    }
    print!("portcourt-gate: self-check against own config ... ");
    let built = run(Command::new("cargo").args(["build", "--quiet"]).current_dir(&root));
    let selfcheck = built
        && Command::new(root.join("target/debug/portcourt"))
            .args(["check", "portcourt.selftest.toml"])
            .current_dir(&root)
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
    if selfcheck {
        println!("ok");
    } else {
        println!("FAIL");
        ok = false;
    }
    if ok {
        println!("\nPORTCOURT-GATE: PASS");
        ExitCode::SUCCESS
    } else {
        println!("\nPORTCOURT-GATE: FAIL");
        ExitCode::FAILURE
    }
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match (args.first().map(String::as_str), args.get(1).map(String::as_str)) {
        (Some("docs"), Some("generate")) => docs_generate(),
        (Some("docs"), Some("check")) => docs_check(),
        (Some("gate"), _) => gate(),
        _ => {
            eprintln!("usage: xtask <docs generate|docs check|gate>");
            ExitCode::FAILURE
        }
    }
}
